jobs:
  - name: devcram-manifest
    type: manifest
    steps:
     - IN: devcram-web
     - IN: gearmand
     - IN: redisd
     - IN: web-docker-opts
       applyTo:
          - devcram-web
     - IN: g-docker-opts
       applyTo:
          - gearmand
          
     - IN: r-docker-opts
       applyTo:          
          - redisd
     - TASK: managed

  - name: dev-deploy
    type: deploy
    steps:
      - IN: devcram-manifest
      - IN: docker-opts
      - IN: devcram-clus
      - TASK: managed
        deployMethod: upgrade
